# TODO: colors
"$schema" = "https://starship.rs/config-schema.json"

palette = "nordic"
format = """
($hostname  )$username  ${custom.folder_symbol}$directory\
$fill\
$git_branch  $git_status\
$line_break $character
"""
right_format = "$cmd_duration"
continuation_prompt = "[┃]() "

[palettes.nordic]
black = "#191D24"
bright-black = "#242933"
grey = "#3B4252"
bright-grey = "#4C566A"
white = "#D8DEE9"
bright-white = "#E5E9F0"
blue = "#81A1C1"
bright-blue = "#88C0D0"
cyan = "#8FBCBB"
bright-cyan = "#93CCDC"
red = "#BF616A"
bright-red = "#D06F79"
orange = "#D08770"
bright-orange = "#D79784"
yellow = "#EBCB8B"
bright-yellow = "#F0D399"
green = "#A3BE8C"
bright-green = "#B1D196"
purple = "#B48EAD"
bright-purple = "#C895BF"

[hostname]
format = "[](fg:bright-orange)[  $hostname ]($style)[](fg:bright-orange)"
style = "fg:bright-black bg:bright-orange"

[username]
format = "[](fg:yellow)[  $user ]($style)[](fg:yellow)"
style_root = "fg:bright-black bg:yellow"
style_user = "fg:bright-black bg:yellow"
show_always = true

[custom.folder_symbol]
command = 'git rev-parse --is-inside-work-tree &>/dev/null && echo "󰊢" || echo ""'
format = "[](fg:green)[ $output]($style)"
style = "fg:bright-black bg:green"
when = true

[directory]
format = "[ $path ($read_only )]($style)[](fg:green)"
style = "fg:bright-black bg:green"
read_only = "󰌾"
truncation_symbol = "…/"

[fill]
symbol = " "

[git_branch]
format = "([](fg:blue)[ $symbol $branch(:$remote_branch) ]($style)[](fg:blue))"
symbol =""
style = "fg:bright-black bg:blue"

[git_status]
format = "([](fg:purple)[( $staged)( $untracked)( $deleted)( $modified)( $renamed)( $stashed)( $conflicted)( $diverged)( $ahead)( $behind) ]($style)[](fg:purple))"
style = "fg:bright-black bg:purple"
ahead = "⇡"
behind = "⇣"
conflicted = ""
deleted = ""
diverged = "⇕"
modified = ""
renamed = ""
staged = ""
stashed = ""
untracked = ""

[cmd_duration]
format = "[$duration]($style)"
style = "fg:bright-grey"

[character]
success_symbol = "[➜](fg:white)"
error_symbol = "[➜](fg:white)"
vimcmd_symbol = "[➜](fg:white)"
